### ISSUE TITLE
module unload dauert zu lang

### ISSUE THREAD

**Issue by marcelloceschia** [marcelloceschia/chan-sccp-b#153]
mit 10 devices und runtime ~12h dauert der unload 15sek

**Comment by dkgroot** [comment]
Gibt es diesem problem noch. Habe dies schon lange nicht mehr gesehen. Mein testserver lebt aber meistens nicht so lange. Konnte dies auf der testserver nicht reproduzieren um ehrlich zu sein (uptime multiple weeks/months).

**Comment by dkgroot** [comment]
Revised the way we stop the socket_accept thread, this has sped up unload the module considerably. Closing issue for now.
