### ISSUE TITLE
Ringtone in and out of band

### ISSUE THREAD

**Issue by dkgroot** [marcelloceschia/chan-sccp-b#228]
Report: Marcello and Nikolay Vasilev
Date: 2014-08-11
Related to: #229

Nikolay has noticed that the issue is resolved when switching from earlyrtp=progress to earlyrtp=ringout

Nikolay Report:
1.      It seems that 7911 is affected by dual ringing and 7912 is not
2.      If I put Progress() on top of my dial plan the issue disappears
3.      In file sccp_indicate.c line 158 if I always return sccp_channel_openReceiveChannel(c) instead of sccp_dev_starttone(d, (uint8_t) SKINNY_TONE_ALERTINGTONE, instance, c->callid, 0) the issue disappears
4.      No matter thru how many sip trunks the media goes is the setting earlyrtp is set to progress in sccp.conf on the last node the the issue is appearing

**Comment by dkgroot** [comment]
Haven't seen this on the mailinglist anymore. I just experience it went dialing onhook though, so i guess it is still there.

**Comment by dkgroot** [comment]
references #5933

**Comment by marcelloceschia** [comment]
ich werde ein update machen und noch mal testen

**Comment by marcelloceschia** [comment]
problem weiterhin vorhanden

**Comment by dkgroot** [comment]
Bei mir hatt es ein case mit  gelost,  Wobei mann warend dialen, nummer unbekannt bekommen hatt, und es hatt dann einfach weiter gemacht.
