### ISSUE TITLE
Invalid SCCP message! : ID :9a

### ISSUE THREAD

**Issue by marcelloceschia** [marcelloceschia/chan-sccp-b#280]
1417: CRT 18:12:36.537219 JVM: Startup Module Loader|cip.sccp.ah@131ba1:createMessage - No entry in hashtable for ID=0x9a
1418: WRN 18:12:36.538816 JVM: Startup Module Loader|cip.sccp.co:? - Invalid SCCP message! : ID :9a: MessageFactory.createMessage failed, length = 0 - close connection and alarm in future
1419: ERR 18:12:36.543793 JVM: 18:12:36|cip.sccp.bd: ID :9a: MessageFactory.createMessage failed, length = 0

**Comment by dkgroot** [comment]
Do you know which two messages these are  (DynamicNotify and ClearDisplay ?)
ProtocolVersion ?

**Comment by marcelloceschia** [comment]
0x9a

**Comment by dkgroot** [comment]
Taking that as cleardisplay. This device does not seem to know this message, so that's why asked for the protocol version.  Maybe we should have used ClearNotifyMessage on this type of device instead.

**Comment by marcelloceschia** [comment]
ist ein 7975 mit aktuellster firmware
daher aktuelle protokoll version

**Comment by dkgroot** [comment]
Bin gespannt was du dort finden wirst.

**Comment by dkgroot** [comment]
@marcelloceschia : Gab es ibz message "9a" hier noch neuigkeiten. Mussen wir da noch was machen / fixen ?

**Comment by marcelloceschia** [comment]
da müssen wir einfach die phone logs noch mal prüfen

**Comment by dkgroot** [comment]
Ok. War mir nicht ganz deutlich wie/wo wir da geblieben waren :-)

**Comment by dkgroot** [comment]
Dropped usage of this message for all phones, so far no reports about missing functionality. Issue Closed
