### ISSUE TITLE
Disable cfwdall from CLI

### ISSUE THREAD

**Issue by dkulemin** [marcelloceschia/chan-sccp-b#462]
Hi!
Is there a way to disable call forward all for line from CLI? Tried command "sccp set device SEPXXXXXXXXXXXX cfwdall off", but it just makes CFwdALL service unavailable from device and call forwarding is still enabled.

Thanks!

**Comment by dkgroot** [comment]
That sounds like a regression.. I will have a look at it tomorrow, to see what i can do.

In the meantime you might consider doing:
```
CLI> database show
CLI> database deltree SCCP/SEPxxxxx cfwdAll
CLI> database deltree SCCP/SEPxxxxx cfwdBusy
CLI> sccp restart SEPxxxxx
```
For all the devices in question, that should also do the trick.
Sorry about the inconvenience.

BTW: You are welcome to join us at [gitter chan-sccp chatroom](https://gitter.im/chan-sccp/chan-sccp) :-)

**Comment by dkgroot** [comment]
@dkulemin There currently is no method implemented to set/remove callforward from device/lines on the CLI. In retrospect i think that's a flaw that should be corrected, but it will take me a little bit to add it. Thanks for bringing it to my attention. I will let you know as soon as we have something.

**Comment by dkulemin** [comment]
@dkgroot Thanks for the answer! And thanks for inviting in chatroom :)

**Comment by dkgroot** [comment]
I will try to make some time to add this little feature somewhere this week. You should be ok, using the database solution for now i guess. 

Background Info: the astdb is used to store these settings temporarily so that we can recover them after an asterisk restart. So to get rid of them, you have to clean them out manually and restart chan-sccp or the device in question.

**Comment by dkgroot** [comment]
Added CLI sccp callforward <lineName> [deviceid] [none|all|busy] [destination]
Added AMI SCCPCallForward: Line, Device, Type, Destination

Example:
```
CLI> sccp callforward 98051 none
CLI> sccp callforward 98051 all 0714343433
CLI> sccp callforward 98051 SEP232332223 none
CLI> sccp callforward 98051 SEP232332223 busy 0714343433
```
@dkulemin Thanks for reporting the issue.
