### ISSUE TITLE
Missing dependencies on Fedora 30 / Asterisk 16.4

### ISSUE THREAD

**Issue by thelan** [marcelloceschia/chan-sccp-b#470]
Unable to load module due to missing dependencies

It seems that the modules has been splitted (plain/imap/odbc)

See: https://src.fedoraproject.org/rpms/asterisk/blob/f30/f/asterisk.spec#_683

**Reproduction Steps:**

1. Install Asterisk from fedora 30
2. Compile and install chan-sccp
3. Load the module

**chan-sccp version:** develop (3f6571112b902813c313747ff37fc567f78658c9)

**asterisk version:** 16.4.0 (bundled in fedora 30 package)

**Observed behavior:**

```
asterisk*CLI> module load chan_sccp.so
Unable to load module chan_sccp.so
Command 'module load chan_sccp.so' failed.
[Aug 21 23:03:42] ERROR[1791]: loader.c:170 module_load_error: chan_sccp has one or more unknown dependencies.
```

**Workarround:**

I've managed to load the module by changing the dependancy list to match `app_voicemail_plain` instead of `app_voicemail` but i think this may need further checking against other names.
File :
https://github.com/chan-sccp/chan-sccp/blob/3f6571112b902813c313747ff37fc567f78658c9/src/pbx_impl/ast116/ast116.c#L3873

**Comment by dkgroot** [comment]
@thelan Hi Julian,

Thanks for reporting this issue and figuring out a potential fix. 

I dropped "app_voicemail" as a requirement, and moved it into ".optional_modules". That should take care of it. Note: I was not able to find 'app_voicemail_plain' anywhere in  the asterisk source, so not sure where this is coming from.

The commit will auto close this issue, if the issue does continue, please reopen it.
