### ISSUE TITLE
Capture ext between SCCP and SIP

### ISSUE THREAD

**Issue by mmguglielmi** [marcelloceschia/chan-sccp-b#472]
I can't capture between SCCP and SIP

**Reproduction Steps:**

1. ext 101 ring (SCCP)
2. 101 answer, then transfer ext 200 (SIP)
3. ext 212 (SCCP) try to capture (with *8 or CISCO capture  button), and not work
I attach asterisk log of both ( *8 and capture button)

Should I have any special consideration in config?

[with ast 8.txt](https://github.com/chan-sccp/chan-sccp/files/3567295/with.ast.8.txt)
[with CISCO button.txt](https://github.com/chan-sccp/chan-sccp/files/3567296/with.CISCO.button.txt)

Thanks in advance for your help
Regards
Marco

**Comment by dkgroot** [comment]
Hi @mmguglielmi ,

If by "capture" you mean gpickup/pickup. You can use so called directed pickup by pressing the PICKUP and entering the number of the RINGING extension you would like to answer (you need to make sure that the correct directed_pickup_context matches the SIP context of the call you would like to answer).

Or if you want to use GPICKUP, you need to make sure that:
the sccp line you are using is a (names) 'pickupgroup' which matches the (named) 'callgroup' of the phone you would like to answer. So to answer a remote SIP call, you need to 
sip.conf
```
[sipuser]
...
callgroup=1
pickupgroup=1
```

sccp.conf
```
[line1]
...
callgroup=1
pickupgroup=1
directed_pickup=true
directed_pickup_context=from-internal-xfer
pickup_modeanswer=true
```
This will allow you to gPickup a call from a remote RINGING sip call. You can also use named call/pickup groups (see asterisk documentation.

If by "capture" you mean something else then please re-explain.

**Comment by dkgroot** [comment]
@mmguglielmi Any update ? Can this issue report be closed ?

**Comment by mmguglielmi** [comment]
Hi @dkgroot 
Thanks for asking
We're doing few more test, and I'll update
The problem continue, but I want to give you more info...
Thanks a lot

**Comment by mmguglielmi** [comment]
Hi @dkgroot
We were making a mistake in the config you suggested
It's working now
I really appreciate your answer
Thanks a lot

**Comment by dkgroot** [comment]
Ok, thanks for the update. Good luck using chan-sccp !
Closing this issue
