### ISSUE TITLE
Autoprovision

### ISSUE THREAD

**Issue by anutator** [marcelloceschia/chan-sccp-b#475]
Simple script to make SEP files from sccp.conf
Not an issue))
Maybe you can make it better ant correct my script, because I am the beginner in Linux.
You must create templates in /tftpboot for different phone models and default template when somebody doesn't use template such as (7911) in sccp.conf
```
SEP_sccp7911.cnf.xml
SEP_sccp7925.cnf.xml
SEP_sccp.cnf.xml
```
etc.

In sccp.conf at first I make templates for phones and lines.
```
[7925](!)
option=....

[7911](!)
option=...
```

Then I add phones with mac addresses and lines.
```
[SEPmac-address1](7911)   ; my comment
description=.... etc.

[SEPmac-address2](7925)  ; my comment
description=.... etc.
```

In script I search for strings which begin with **[SEP**  using egrep. Then I use awk to extract text from brackets [...] and () and save the result in file _temp_:
```
SEPmac-address1 7911
SEPmac-address2 7925
```
Now I use read to echo text on the screen and make links to template xml files.
So the name of model, for example 7911, is the simultaneously a template in sccp.conf and also the part of name in /tftpboot. Make short alias and use it after making changes in sccp.conf
```
#!/bin/bash
# generate SEPmac-address.cnf.xml in /tftpboot from sccp.conf
# Anna Toropova
cd /tftpboot
egrep '\[SEP(.*?)\]' /etc/asterisk/sccp.conf | awk -F '[][]|[()]' '{print $2,$4}' > temp

while read mac model;do
echo "ln -sf SEP_sccp$model.cnf.xml $mac.cnf.xml"
ln -sf SEP_sccp$model.cnf.xml $mac.cnf.xml
done < temp

rm -f temp
```

**Comment by dkgroot** [comment]
@anutator
Very nice idea !
This might be something for our wiki, btw (if you like). 

I just had a little idea for you, to make it easier to parse things separately (and sync later on):
sccp.conf
```
[general]
...
#include /etc/asterisk/sccp/SEP*.conf
#include /etc/asterisk/sccp/LINE*.conf
```
You can then can create a SEPxxxxx.conf file per device and a LINExxxx.conf file per line.

Also you can set 
```
[SEPxxxxxxxxxx]
type = device
devicetype = 7961
...
```
Putting this in seperate files makes it really easy to verify if you have created all of them.

**Comment by dkgroot** [comment]
Some suggestions:
```bash
#!/usr/bin/env bash          # using "env" to call bash. On BSD systems bash is installed in /usr/local/bin/bash and not /bin/bash, so would fail
# generate SEPmac-address.cnf.xml in /tftpboot from sccp.conf
# Anna Toropova
set -e                               # immediately quit if anything goes wrong, during execution
CONFFILE=/etc/asterisk/sccp.conf
TFTPDIR=/tftpboot
if [ ! -f ${CONFFILE} ]; then
   echo "ERROR: ${CONFFILE} could not be found"
   exit 1
fi
if [ ! -d ${TFTPDIR} ]; then
   echo "ERROR: ${TFTPDIR} could not be found"
   exit 2
fi

pushd ${TFTPDIR}           # always use pushd, so you can return to the calling site after the script, using popd
find ${TFTPDIR} -maxdepth 1 -lname 'SEP*.cnf.xml' -delete
egrep '^\[SEP(.*?)\]' ${CONFFILE} | awk -F '[][]|[()]' '{print $2,$4}' | while read mac model
do
        if [ -f SEP_sccp${model}.cnf.xml ]; then
                echo "ln -sf SEP_sccp$model.cnf.xml $mac.cnf.xml"
                ln -sf SEP_sccp$model.cnf.xml $mac.cnf.xml
        else
                echo "ERROR: SEP_sccp${model}.cnf.xml template file, could not be found in ${TFTPDIR}"
                # exit 3 # we could exit or just report the problem and continue.
        fi
done
popd                                  # here we pop back to the directory from where the script was called.
```
I kept all the functionality of your script, just added some safefy checks and clean handling.

**Comment by anutator** [comment]
Thank you for ideas!

I use this options in model templates:
```
[7965](!)
type = device
devicetype = 7961
...
```

**Comment by dkgroot** [comment]
Yes that would work, and nice to see somebody understanding and using asterisk config templates :-)
I have my config in the realtime database (postgres), so can't really use your script. But i have something similar.

Note: I did not want to criticize your script.  You mentioned you were new to linux/unix/scripting, and i thought i could help you by showing a couple of simple small improvements. You already figured out the difficult stuff (egrep / regex / awk) :+1: .

BTW: If you don't mind ugly regex-es, you can do it all in one go:
```
sed -n 's/\[SEP\(.*\)\](\(.*\))/SEP\1 \2/p' ${CONFFILE} | while read mac model
do
   ...
done
```

FYI: if you enjoy doing provisioning stuff and would like to extend your knowledge. You can have a look at [provision_sccp](https://github.com/dkgroot/provision_sccp) which uses nginx + tftpd-hpa + regexes, to allow you to cleanup your /tftpboot directory. We should be able to integrate your auto_provision_script into it, if you like. This project could use a little love and attention (a README.md for starters etc).

**Comment by dkgroot** [comment]
Thank you for the script / insight. I think the best way forward for it would be a page on our wiki (if you need help let me know), or merging this type of solution into [provision_sccp](https://github.com/dkgroot/provision_sccp). 

Note: Will be closing this issue report in 1 week, as it is not really an issue (to be honest).

**Comment by dkgroot** [comment]
@anutator
Thank you for your contribution. Nobody will find the script sample in our issue database though. So please consider writing a post on our wiki or move this script into the provision_sccp repository.

Closing this issue report for now.

**Comment by anutator** [comment]
Forgotten...
You must add a line to delete old links:
`find ${TFTPDIR} -maxdepth 1 -type l -delete`
This will help if we deleted phone from sccp.conf
Besides, if you want to delete phone you must delete line with [SEP....] because if you only comment lines with phone description your script will make the symlink again. Or you must change the script to parse only lines which begin with **[SEP** and not **;[SEP**,
Maybe add ^ to egrep expression

**Comment by dkgroot** [comment]
Nice addition ! What line should the `find` go on ?
Added '^' to the front of the egrep, that should take care of the remarking.

**Comment by anutator** [comment]
I added line with find...  before pushd.
```
find ${TFTPDIR} -maxdepth 1 -type l -delete
pushd ${TFTPDIR}  
```
But I think we can add it after pushd and find in current directory
```
pushd ${TFTPDIR}  
find . -maxdepth 1 -type l -delete
```
Besides we must be shure that we have only links created by Asterisk in tftpboot directory. If we created other links ourselves we must add -name "SEP*" to find command.

**Comment by dkgroot** [comment]
Updated the example file :-) Added `-iname "SEP*.cnf.xml"`  to make sure we don't delete other softlinked files

**Comment by anutator** [comment]
Today I found special option **-lname**, so you don't have to use two options.
> -lname pattern
> File is a symbolic link whose contents match shell pattern. The metacharacters do not treat `/' or `.' specially.  If the -L option or the -follow option is in effect, this test returns false unless the symbolic link is broken.

You should change line to:
`find ${TFTPDIR} -maxdepth 1 -lname 'SEP*.cnf.xml' -delete`

**Comment by dkgroot** [comment]
@anutator 
Thanks, updated the script, as you are the originator of this issue report, you should also be able to edit the script above (i think). I hid some of the posts, so the important part is more visible.

**Comment by dkgroot** [comment]
Closing issue. Not sure what to do with the script atm
