### ISSUE TITLE
openSUSE name is misspelled in the readme file

### ISSUE THREAD

**Issue by m-rey** [marcelloceschia/chan-sccp-b#480]
`openSUSE` is written as `OpenSuSE` in the readme file.
The spelling can easily be checked by pressing the openSUSE links and checking that the linked openSUSE website spells it `openSUSE`

**Comment by dkgroot** [comment]
I think there was a time (way back when) when it was the other way around. Then again Suse has changed their name a couple of times :-)
Thanks for the Issue and subsequent PR though ! Merged !

BTW: These kinds of small PR's are always welcome :-)

FYI: Kurz nachgeschaut, und: S.u.S.E. war (anfangs) ein Akronym für "Software und System-Entwicklung". Nach der Übername durch Novell, hat der Name sein Akronym Status verloren und ging nur weiter unter SUSE. Vielleicht bin ich einfach alt und habe ich schon vor der Übername mit SuSE gearbeitet :-)
