### ISSUE TITLE
sccp_enum generation fails with 'mawk' NOT-A-NUMBER

### ISSUE THREAD

**Issue by snuffy44** [marcelloceschia/chan-sccp-b#485]
Using Debian 8.11 with default mawk/awk.
\[:xdigit:\] is not recognized causing compile error.

**Reproduction Steps:**

1. Force use of mawk
2. Try to generate sccp_enum.[ch]
3. Resulting sccp_enum.[ch] produces whole lot of NOT-A-NUMBER

**chan-sccp version:** develop branch

**asterisk version:** (include revision and/or branch if relevant)

**Expected behavior:**

Should correctly create the .c/.h files

**Observed behavior:**

inside sccp_enum.c:
ie. uint32_t value_map[] = {NOT-A-NUMBER,NOT-A-NUMBER,NOT-A-NUMBER,NOT-A-NUMBER,NOT-A-NUMBER,NOT-A-NUMBER,NOT-A-NUMBER,NOT-A-NUMBER,NOT-A-NUMBER,NOT-A-NUMBER,NOT-A-NUMBER,};

**Addition / Optional Information:**
- Problem started happening recently, didn't happen in an older version of Chan-SCCP: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes
- Platform:
 - Debian 8.11  amd64

**Comment by snuffy44** [comment]
Related to this new commit I believe: ee1087e656f4561419f68506c9b86f587dfd7947

**Comment by dkgroot** [comment]
@snuffy44 
The enum generation script is based on the GNU awk version (gawk). Can you check if `gawk` is available on your system.
You can run the generation script manually from the command line, using:
`gawk -f "tools/gen_sccp_enum.awk" < src/sccp_enum.in`

**Comment by snuffy44** [comment]
Tested - Works fine with gawk

**Comment by dkgroot** [comment]
> Related to this new commit I believe: [ee1087e](https://github.com/chan-sccp/chan-sccp/commit/ee1087e656f4561419f68506c9b86f587dfd7947)

Aah ok, super. Then we need to fix the configure script, to search for gawk instead of awk/mawk. This will be a little annoying on other platforms like BSD though.

We can have another look at making the script generic awk compatible later.

**Comment by snuffy44** [comment]
mm wouldn't doing just [0-9a-fA-F] work instead of xdigit?

**Comment by dkgroot** [comment]
I think you are right. 
Can you give that a go ? And see if it works with standard awk/mawk ?
BTW: You might have to allow for 0xAbc123bD to cover hex

**Comment by snuffy44** [comment]
changing line 27 to  /^0[xX][0-9A-Fa-f]+$/ works fine..
Have actual values again.

**Comment by dkgroot** [comment]
Looks like your fix works. Will make the change in a couple of seconds.

FYI: It's so easy to fall for these nice little `enhancements` provided by some tools, and they slowly lure you away from the minimal standards.

**Comment by dkgroot** [comment]
Pushed your fix ! Thanks a lot

Always nice to get help fixing an issue from the issue owner.
