### ISSUE TITLE
error compiling develop branch / Device disconnect during Call / Looping / Refcount

### ISSUE THREAD

**Issue by rofferman** [marcelloceschia/chan-sccp-b#488]
I get the following error when I compile the latest develop branch
Freepbx 15.0.16.22
Asterisk 16.6.0
CentOS 7

make -j4
```
Making all in src
make[1]: Entering directory `/usr/src/chan_sccp/src'
make  all-recursive
make[2]: Entering directory `/usr/src/chan_sccp/src'
Making all in pbx_impl
make[3]: Entering directory `/usr/src/chan_sccp/src/pbx_impl'
make[3]: Nothing to be done for `all'.
make[3]: Leaving directory `/usr/src/chan_sccp/src/pbx_impl'
Making all in pbx_impl/ast
make[3]: Entering directory `/usr/src/chan_sccp/src/pbx_impl/ast'
  CC       libast_la-ast.lo
In file included from ../../../src/common.h:34:0,
                 from ast.c:12:
ast.c: In function âget_sccp_channel_from_pbx_channelâ:
../../../src/define.h:180:2: error: â__auto_typeâ undeclared (first use in this function)
  __auto_type __attribute__((unused)) __dummy = (_T)(_ptr); \
  ^
../../../src/sccp_refcount.h:75:13: note: in expansion of macro âPTR_TYPE_CMPâ
  pbx_assert(PTR_TYPE_CMP(const _type *const, (_x) ) == 1);           \
....
ast.c: At top level:
cc1: warning: unrecognized command line option "-Wno-format-truncation" [enabled by default]
make[3]: *** [libast_la-ast.lo] Error 1
make[3]: Leaving directory `/usr/src/chan_sccp/src/pbx_impl/ast'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/usr/src/chan_sccp/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/usr/src/chan_sccp/src'
make: *** [all-recursive] Error 1
```

**Comment by dkgroot** [comment]
@rofferman Aaah mann, is Centos still using these lame old compilers. I will revert the change (for now). But centos should get the behind in motion and move toward the 21 century.

**Comment by rofferman** [comment]
Ok, its acutally Sangoma OS lol. 
Can I install the correct compilers on Centos?

**Comment by dkgroot** [comment]
Reversion is done... Latest version should compile again, even with the compilers you had/have already.

And yes you can if you want to. We have had issues with old compilers on Centos before: See [Update-Compiler---Devtools-on-CentOS](https://github.com/chan-sccp/chan-sccp/wiki/Update-Compiler---Devtools-on-CentOS). Same repo should still apply (i hope).

'\_\_auto_type' has been supported in gcc and clang in (at least) the last three major compilers versions, so i assumed everybody would be on one of them by now.

**Comment by dkgroot** [comment]
Pretty happy with the turn around on this issue report though.. 9 minutes, not bad :-). And thank you for including the correct information to make that possible.

**Comment by rofferman** [comment]
Yes that is awesome, thank you so much

I have a weird issue also and I can create another ticket if need be , but what Is registration rejected: crossover session mean. I have just encountered this on one phone so far. I changed the switch port and still get it?

Phones are 7975 and 7942

**Comment by rofferman** [comment]
Yes that is awesome, thank you so much

I have a weird issue also and I can create another ticket if need be , but what Is registration rejected: crossover session mean. I have just encountered this on one phone so far. I changed the switch port and still get it?

Phones are 7975 and 7942

**Comment by dkgroot** [comment]
@rofferman 
I normally stop looking at closed issues :-)
A crossover session should be resolved automatically. It happens when the connection between the server and phone gets seperated, but the device information has not yet been cleaned up. We start the cleanup process at that moment, and tell the phone to return 60 seconds later and try again.

It's existence is something that i am not to happy about, but because re-creating this situation is impossible (as far as i know), it happens very sporadically. Which makes it hard to clean this part of the code up or make it better.

**Comment by dkgroot** [comment]
If this issue is persistent and not just a question, then yes we should open a new issue report for this, instead of continuing on an existing (and already closed) one.

**Comment by rofferman** [comment]
Its not going away. I will try and restart asterisk in abit and see if that fixes it.. 
If not I will open a different ticket

I also updated my compiler on Centos

**Comment by dkgroot** [comment]
Ok then a reset will 'fix' it for sure, the question is how we got in this state. What sccp debug level were you running before it happened ?

**Comment by rofferman** [comment]
Debug was set to all I believe

**Comment by dkgroot** [comment]
Ooh that's good (in this case) Can you find the stop in the debug log file just before it started happening and then send me an excerpt of what went on (let's say 15 before and 15 min after the first case)

**Comment by rofferman** [comment]
Here is some of the debug log when the clean was not working on extension 3525
[new 1.txt](https://github.com/chan-sccp/chan-sccp/files/3806363/new.1.txt)

**Comment by dkgroot** [comment]
Just mail me the whole debug log, and tell me the device SEP to look for and the line(s) attached to it, so i can search through it. (ddegroot@talon.nl)

**Comment by dkgroot** [comment]
After that you can restart the asterisk server and you should be ok.

**Comment by rofferman** [comment]
I sent the log to you via wetransfer. It was 180 MB. 
The offending Sep addresss is SEP00083031F110

A asterisk restart seemed to of fixed the problem.

**Comment by dkgroot** [comment]
Ok downloading now. You can compress a log file you know :-)
This is going to take me quite a while to sift through. Which line is attached to this device ? And what extension ?

**Comment by rofferman** [comment]
The line is 812-492-3525
Ext 3525

And I didn't even think about compressing it.. That was too obvious lol

**Comment by dkgroot** [comment]
If you like you can activate rotate in /etc/asterisk/logger.conf so that log files are broken up every XX Mb's and then compressed automatically. Might save some diskspace and search time in the future.

**Comment by dkgroot** [comment]
@davidded 
Excerpt from the full log.
[analysis_full_20191105.zip](https://github.com/chan-sccp/chan-sccp/files/3810784/analysis_full_20191105.zip)

We are looking for:
line: 3525
device: SEP00083031F110
linedevice: SEP00083031F110/3525

in the excerpt the refcount is going out of control at [2019-11-04 12:42:28]

**Comment by dkgroot** [comment]
@rofferman Thanks to your full log with the high debug setting, we may have an inroads to fixing this looping/reset/cleaning cycle.

**Comment by rofferman** [comment]
That's great. Thanks for the help

**Comment by dkgroot** [comment]
It will take a while to go through it all, so please give me a couple of days to figure this out !

**Comment by dkgroot** [comment]
@davidded 
might have found the first clue:
```
[2019-11-04 12:40:30] NOTICE[9230][C-0000002f] sccp_session.c:     -- SEP00083031F110: Connection reset by peer
[2019-11-04 12:40:30] NOTICE[9230][C-0000002f] sccp_session.c:     -- SEP00083031F110: Exiting sccp_socket device thread
```

Happens in the middle of a hangup (before it ends)
And then during the device cleanup (we rename the device) so a subsequent sccp_device_findbyid will not be able to find the 'old' reference).
```
[2019-11-04 12:40:30] NOTICE[9230][C-0000002f] sccp_channel.c:   == XXX00083031F110: Ending call SCCP/3525-000001F8 (state:CONGESTION)
[2019-11-04 12:40:30] NOTICE[9230][C-0000002f] sccp_channel.c:     -- XXX00083031F110: Sending hangupRequest to Call SCCP/3525-000001F8 (state: CONGESTION)
```
Pretty sure we do something bad after that, linking them back up again, were we should.
Yep this does not make much sense (yet), referring to the same device by two different name in two different threads. This will not end well
```
2019-11-04 12:40:30] VERBOSE[9230][C-0000002f] sccp_refcount.c:  ast.c          :0643 (sccp_astgenwrap_requestQueueHangup ) <----                  refcount decreased 04  <- 05 for    channel: SCCP/3525-000001F8 (0x7f02e000c260)
[2019-11-04 12:40:30] NOTICE[7661] sccp_device.c:     -- SEP0021A0103BFE: >> Send message SpeedDial State Dynamic Message
[2019-11-04 12:40:30] VERBOSE[9230][C-0000002f] sccp_refcount.c:  sccp_channel.c :1468 (sccp_channel_endcall               ) <------------          refcount decreased 12  <- 13 for     device: SEP00083031F110 (0x7f02e0002f00)
[2019-11-04 12:40:30] NOTICE[7661] sccp_session.c: SEP0021A0103BFE: Send Message: SpeedDial State Dynamic Message(0x0146) 140 bytes length
[2019-11-04 12:40:30] VERBOSE[9230][C-0000002f] sccp_refcount.c:  sccp_device.c  :2439 (_sccp_dev_clean                    ) <-----------           refcount decreased 11  <- 12 for     device: SEP00083031F110 (0x7f02e0002f00)
[2019-11-04 12:40:30] VERBOSE[9230][C-0000002f] sccp_refcount.c:  sccp_device.c  :2437 (_sccp_dev_clean                    ) <---                   refcount decreased 03  <- 04 for    channel: SCCP/3525-000001F8 (0x7f02e000c260)
[2019-11-04 12:40:30] VERBOSE[18391][C-00000004] pbx.c: Spawn extension (from-internal, 35, 7) exited non-zero on 'SCCP/3525-000001F8'
[2019-11-04 12:40:30] NOTICE[9230][C-0000002f] sccp_device.c:   == SCCP: Remove Line 3525 from device XXX00083031F110
[2019-11-04 12:40:30] NOTICE[9230][C-0000002f] sccp_linedevice.c:     -- XXX00083031F110: remove device from line 3525
```
I will dissect this further tomorrow. At least we know where to look and what to look for (i think)

**Comment by dkgroot** [comment]
Related Issues: #483 / #482 / #333 
Finally we have debug log to analyse regarding device restart / looping / reregister.

**Comment by rofferman** [comment]
This happened to me again this morning, I have other installations of chan sccp that I use and they do not have this issue. Is there a trigger that causes this to happen?

**Comment by dkgroot** [comment]
@rofferman
I have not had time to fully analyze the log and come up with a possible fix yet. I have been down with the flu over the weekend. Also 'this' is not very clear on an issue report containing more than one issue, so i don't if you are talking about a compile issue or the last problem you reported, regarding looping/cleanup cycle (that's one of the reasons i don't really like having multiple issues in a single issue report :-)).

**Comment by rofferman** [comment]
The looping/cleanup cycle,
Came  in this morning to phones stuck in crossover session
I hope you are feeling better and don't mean to bother, just wanted to checkin on the issue

**Comment by dkgroot** [comment]
No problem. Sorry you ran into the same issue again. I will report back as soon as i have had time to go over the log in detail and figure out the cause. In the meantime, you might want to compare the logs and see if you can see if there is some similar behaviour before running into the issue (for example the same device/line combination being involved or doing a callforward or transfer). Sorry i don't have a ready made solution for the issue right now.

**Comment by dkgroot** [comment]
@rofferman I have rewritten some of the hangup handling. Note sure if this is going to help fix the issue, but from analyzing the debug log, i noticed that when the hangup failed at some time, all the subsequent hanging up caused new and more problems. I have added a debug log, to print the variables related to channels and hangup under the sccp log 'pbx' keyword.

***Git***
_Checkout this temporary branch_
```
git pull
git fetch -a
git branch
git checkout issues/488
./configure [....]
make -j4 && make install && make reload
```

_move back to develop afterwards:_
```
git checkout develop
```

If possible use the same debug settings you used previous (or at least sccp.conf `debug=core,pbx,channel,device,line,refcount,pbx`). I am curious to see if the looping still occurs or this helps to reduce the issue or maybe even resolve it.

**Comment by rofferman** [comment]
Great,, So you want me to pull that version. Run Debug for a while on it, Send you the Debug log from that version, then switch back to develop.
Is that correct?

**Comment by dkgroot** [comment]
Please make sure you run a couple of tests before putting in production  (if in corporate environment). If it works without side effects, we should merge the changes, so don't switch back to develop just yet, only when encountering more issues

**Comment by rofferman** [comment]
Ok do you want the debug log or part of if it when or is that not necessary if there are no issues

**Comment by dkgroot** [comment]
If you have the space, yank the debug up nice and high :-) Especially in the beginning to see if there are negative side effects. Once it stabilizes we need to figure out if the old looping issues still occur. I only need the debug log when/if it goes wrong :-)

**Comment by rofferman** [comment]
Ok its implemented and I will keep you posted, Debug is set to all.
instead of make reload can you do a chan_sccp module reload.
I cant take the system down right now

**Comment by dkgroot** [comment]
You can do a module unload / load but the sccp phones will have to be dropped and reregister. If that is not allowed at the moment, then you will have to wait.
In the meantime it might be a good idea to clone the machine and setup a test server (if you are running on a VM).

**Comment by rofferman** [comment]
Yes i am doing a clone right now

**Comment by dkgroot** [comment]
Pushed another little update, to get more information when something does go wrong.

**Comment by rofferman** [comment]
great. I just pulled it
so far so good

**Comment by dkgroot** [comment]
Ooh good news. This is on production or your test-clone ?
What was your previous 'uptime' compared to now ?

**Comment by rofferman** [comment]
Production.. and Its not active yet, I have not had a chance to do a make reload. I will do it tonight

**Comment by dkgroot** [comment]
You do know you can schedule a reload using `core restart when convenient` right. It will restart asterisk when there are zero active calls :-) But it would be recommended to have tested the module before doing something like that.

**Comment by dkgroot** [comment]
If your uptime is this important, you might want to look into clustering your asterisk server and make two identical copies next to one another. With quick failover.

**Comment by rofferman** [comment]
yeah I know, its that when it restarts all the phones go down any my users freak.

**Comment by rofferman** [comment]
I do have a warm spare that is backed up to every night thru freepbx

**Comment by dkgroot** [comment]
Push an `SCCP System Message "server maintenance planned at 1:00AM"`  :-)

**Comment by dkgroot** [comment]
Ooh nice, already a good start in that sense. Active/Active clustering is also possible of course, but a little more work.

**Comment by rofferman** [comment]
LOL I should , tomorrow is a holiday though so not problem getting it done soon

**Comment by dkgroot** [comment]
Ooh enjoy you 'partial' day off then :-)

**Comment by rofferman** [comment]
I have only had one or two other instances with the crossover section error since I started this ticket

**Comment by dkgroot** [comment]
But without the problem of it getting stuck ? So should we call that a slight improvement ?

**Comment by dkgroot** [comment]
@rofferman:
I forced a rebase + push, if you want to get the latest version, you need to:
```
git checkout develop
git branch -D issues/488
git pull
git fetch -a
git checkout issues/488
```
it is not absolutely crucial, if you already got the latest from before, the functionality has not changed, i just improved the reporting a little.

Hope to hear if the latest version has improved the situation on your side, and you are not seeing the stuck devices any more.

**Comment by rofferman** [comment]
Got both updates applied and have not had any issues yet
Is there anything I should look for specifically in the debug logs that would help?

**Comment by dkgroot** [comment]
@rofferman
How many calls and how much uptime with the new version ? Should the issue have presented itself yet, if on the old version ?
Look for crossover, followed by a series of crossovers, re-register over and over (ie: looping & stuck) A single crossover and recover is not the issue, this fix was concentrating on. The objective was not to get stuck.

**Comment by dkgroot** [comment]
You can do something like:
`grep -i -e "Connection reset by peer" -e "Sending hangupRequest" -e "is registering -e "Cleaning previous session, come back later" /var/log/asterisk/message`
And see if a device is continuing to have trouble, or it is just a one of re-register.

**Comment by dkgroot** [comment]
@rofferman  Any updates ?

**Comment by rofferman** [comment]
@dkgroot  So far so good. I have not had any problems as of yet..

**Comment by dkgroot** [comment]
I think that means we should merge it back to develop as an improvement.
Should be done in a couple of minutes.
Please move back to develop in 10 min.

**Comment by dkgroot** [comment]
Merged and Pushed. Please switch back to develop branch:
```
git checkout develop
git pull
./configure [...]
make -j4 && make install && make reload
```

**Comment by rofferman** [comment]
Ok thanks, and I will keep an eye on it
