### ISSUE TITLE
What is "empty" softkey supposed to do?

### ISSUE THREAD

**Issue by billsimon** [marcelloceschia/chan-sccp-b#493]
On ring-out, a softkey labeled "Empty" appears in the first softkey slot. Pressing the key during ring-out causes the phone to display "No channel to perform empty on!" and the call fails. The phone is also rendered unusable for about 30 seconds (all buttons inoperative). What is the purpose of this softkey? I intend to adjust the template to remove it, but would like to understand its meaning first.

**Comment by dkgroot** [comment]
@billsimon 
An empty softkey should normally not popup on a phone, and just leave an empty spot, used to line up softkeys nicely. It shoud not have any side effects when pressed either. I am wondering what type of phone you are using, that has this peculiar behavior. You can create a specialize softkeyset if necessary (for now) until we figure this out.

**Comment by dkgroot** [comment]
@darkponay helped clarify the problem :-)

@billsimon Thanks for reporting the issue. Just committed a fix for the problem
The empty button is not suppressed again but still leaving an open space.

**Comment by billsimon** [comment]
Confirmed, problem solved on my phones. Thanks!

**Comment by dkgroot** [comment]
Sorry if took 3 weeks for me to finally understand the problem :-))
