### ISSUE TITLE
cant setup realtime 

### ISSUE THREAD

**Issue by Idkwhattocallme** [marcelloceschia/chan-sccp-b#494]
help i cant set up realtime im following the instructions here
 https://github.com/chan-sccp/chan-sccp/wiki/Realtime-Configuration

but none of the commands work 

i am using asterisk 16 with freepbx

**Comment by dkgroot** [comment]
@Idkwhattocallme Can you give me some more details:
- the platform/version/cpu-arch you are using
- Which commands don't work
- What error you get back
- Please be specific, i am very bad at guessing
- Show the files you have been editing
- If you are using freepbx, you should use the [freepbx guide](https://github.com/chan-sccp/chan-sccp/wiki/FreePBX). Installation of the sccp_manager will take care of most of the setup for you

Helping with realtitime might be easier using [chat](gitter.im/chan-sccp/chan-sccp).

**Comment by Idkwhattocallme** [comment]
i am using freepbx and following the guide but when i try to install sccp_manager i get a error cannot find sccpdevice table

**Comment by dkgroot** [comment]
Which freepbx version. Have you seen the notice in FreePBX_Installation:4b ?
Please log in to the gitter chat make this process a little easier
For help with sccp_manager you might need some help from @PhantomVl and he can be reached in the chat as well.
Note i don't use FreePBX or the sccp_manager plugin, so i don't have much/any experience with it.

**Comment by Idkwhattocallme** [comment]
what is gitter chat

**Comment by dkgroot** [comment]
https://gitter.im/chan-sccp/chan-sccp

**Comment by dkgroot** [comment]
Closing issue because of lack of reply
