### ISSUE TITLE
"Temp Fail" displayed when call is connected

### ISSUE THREAD

**Issue by mpaland** [marcelloceschia/chan-sccp-b#495]
Tested with asterisk 16.6.1 and latest dev chan-sccp as of today.

I have a button as line monitor for a group of other phones belonging to Manfred on my desk phone like:
`button = speeddial, Manfred, 12, 81@ext-hints`

hint 81 in the dialplan is like:
`exten => 81,hint,PJSIP/11&SCCP/12&SCCP/13`

When a call is coming in on the this line it shows in my display:
2132232 ->Manfred

When the call is connected it shows:
Manfred
or
22123322 <=> Manfred
or
"Temp Fail" <=> Manfred

No number is displayed when the call is handled by the PJSIP phone, but I saw "Temp fail" a few times on asterisk 16 lately and am wondering why?

When a call is going out, it always shows:
323232 <- Manfred (when SCCP phone is used)
and just
Manfred (when PJSIP phone is used)

**Comment by dkgroot** [comment]
Ooh that is not good. To be honest i did a little bit of 'optimization' in the sccp_hint.c file a couple of 1-2 weeks ago. But i don't remember if i checked the result, i just looked logical. I will look it up and revert the change and give it a look. Sorry about this  and thanks for reporting the issue.

**Comment by dkgroot** [comment]
Reverted commit 8239b6d
Please let me know if this took care of the problem, assuming it does.

**Comment by mpaland** [comment]
I reviewed your changes, all the fall-through optimizations should be fine. Must be some other change.
Anyway I retest the actual version.

By the way, is the explicit number display configurable?
Sometimes, it would be better not to expose the call details on a monitoring phone, the status of the hint (LED, Line symbol) would be sufficient.

**Comment by dkgroot** [comment]
> I reviewed your changes, all the fall-through optimizations should be fine. Must be some other change.

That's what i thought as well. It was just supposed to be a little cleanup.

> By the way, is the explicit number display configurable?

Eeh yes, but currently it's an all or nothing `./configure --disable-dynamic-speeddial-cid` option. It could be made into a per line, per device or per button kind solution, but that is not present at this time. Would need some discussion and work i guess.
If we want to go there, question one would be, do we suppress it from the supply side (device or line) or the reception side (button).

We could start with supporting 'Private' softkey better if that would help.

**Comment by dkgroot** [comment]
@mpaland 
Had another look at the current code. There is the device->privacy sccp.conf entry. It controls hint cid information. privacy=full means all call info is hidden on remote hinted speeddials, privacy=on means it can be controlled using the 'private' softkey. privacy=off means call info is always shared. I forgot this was added something like 2 years ago. Maybe having this at the device level is not 100% what you were looking for, but it is a start i guess.

You can also define a feature button to control privacy state [See](https://github.com/chan-sccp/chan-sccp/wiki/Button-Configuration):
- `button = feature, "privacy callpresent", privacy, callpresent`
- `button = feature, "privacy hint", privacy, hint`

Note: `sccp debug core,hint,feature,config,device` to see some of the events happen

Questions:
1. is this what you are looking for ?
2. Can you check if this device->privacy is still working correctly ?
3. Can you check the feature button to see if that is still working as described ?
3. can you check out wiki, to see if it is described or needs clarification ? (I think we need a little more in this area).
4. would this need improving by having privacy control on the (sending side) line level ?
