### ISSUE TITLE
DHCPD instead of DHCP on CentOS

### ISSUE THREAD

**Issue by DL3KB** [marcelloceschia/chan-sccp-b#515]
Just a little reminder, that in the installation guide for freePbx the dhcp service in centOs is called dhcpd

**Comment by dkgroot** [comment]
@DL3KB Hi Karim,
Can you change/fix the wiki where it is required. I don't use FreePBX myself, so have not much experience what they use or name stuff.

**Comment by dkgroot** [comment]
@DL3KB Any update ? Have you made any changes to the wiki (and if yes, which pages ?).
Can this issue report be closed ?

**Comment by SlashBuster** [comment]
Yes the problem is dismissed. I updated the instructions

**Comment by DL3KB** [comment]
Problem is resovled I've updated the instructions
