### ISSUE TITLE
Not make outgoing call. Config file ' 7C' not found

### ISSUE THREAD

**Issue by bknv** [marcelloceschia/chan-sccp-b#518]
Hello

Problem:
Cisco phone not make outgoing call, and vanish button on display (clwdall)

**When i enter command asterisk -rx 'core reload' i get error message ERROR**:

sccp_config.c: Config file ' 7C' not found, aborting (re)load.
chan_sccp.c: Error reloading from ' 7C'
chan_sccp.c: Config file ' 7C' not found, aborting reload.

P.S> What is it "' 7C'"?

**if i reload sccp module** :

asterisk*CLI> sccp reload
Command 'sccp reload ' failed.
[2020-05-17 13:16:21] NOTICE[5652]: sccp_cli.c:2854 sccp_cli_reload: GLOB(cfg) not available. Skip loading default setting.

if i reload already connected phone or connected new phone, on display phone vanish button callforward and phone not make outgoing call. Also new phone get default sccp config settings.  

before core reload, settings my phone in [before.txt](https://github.com/chan-sccp/chan-sccp/files/4640084/before.txt)
after core reload and restart my phone, settings my phone in [after.txt](https://github.com/chan-sccp/chan-sccp/files/4640083/after.txt)

Problem solved if restarted asterisk, but appears after core reload.

What is wrong with my asterisk?

**chan-sccp version:** Skinny Client Control Protocol (SCCP). Release: 4.3.2 develop - fdcfaf1
**Sccp manager version:** Sccp Manager V.14.0.0.2 
**asterisk version:** 13.27.1

**Comment by dkgroot** [comment]
@bknv 
@rofferman already reported the issue and it was fixed yesterday. If you pull the latest version, the problem should be resolved. Thanks for posting an issue report though !

> What is wrong with my asterisk?

Nothing, it was an error in chan_sccp, caused in a recent commit, which has now been dealt with.

(Closing the issue for now, if the issue does continue, please reopen).
