### ISSUE TITLE
Cisco 7920 limited to 4 lines

### ISSUE THREAD

**Issue by dunhill52** [marcelloceschia/chan-sccp-b#521]
The old Cisco 7920 supports up to six lines (The screen can display only four lines but you can scroll down).

Currently chan-sccp only allows you to set up 4 lines and discard the additional 2 lines. The problem is in sccp_device.c and quite straightforward to fix it seems:

```c
case SKINNY_DEVICETYPE_CISCO7920:
    for (i = 0; i < 4; i++) {
        btn[btn_index++].type = SCCP_BUTTONTYPE_MULTI;
    }
```

Changing that for 6, I checked that all lines appear in the 7920 and seem functional.

PS: Thank for the great job you do with chan sccp... I love it and use it every day at home.

**Comment by dkgroot** [comment]
@dunhill52 Thanks for reporting the issue, and figuring out the solution as well. Will make the change right now and commit.
