### ISSUE TITLE
2 small problems with dynamic speed dials

### ISSUE THREAD

**Issue by drtmk** [marcelloceschia/chan-sccp-b#533]
Invalid speed dial lamp change during ringing state

**Reproduction Steps:**
Alice calls Bob (ringing state)
All speed dials that have Alice extension configured show: `Bob<-Alice` (and blinking orange)
Charlie dials Alice and gets busy tone (as it should under incominglimit=1), but all speed dials that monitors Alice extension, turns solid red instead of blinking orange although Alice line is still in ringing state.

`
`
Invalid speed dial direction after answering Group Pickup

**Reproduction Steps:**
Alice calls Bob. Charlie presses Group Pickup and anwers that call.
Alice is connected with Charlie, and speed dial that has Charlie extension configured shows `Alice -> Charlie`, instead of `Alice <=> Charlie`.

**chan-sccp version:** 4.3.2 develop - c5c56f4
**asterisk version:** 16.12.0

**Comment by dkgroot** [comment]
@drtmk They are pretty much cosmetic as you mentioned. The first one is interesting and i will have to have a look. The second one might be out of our control, but it's interesting to see if we can do anything about it.
Thanks for reporting both of them.

**Comment by dkgroot** [comment]
Had a look at the first case and came up with a possible solution. We are dealing with an event attached to a line change, which has multiple channels and therefor multiple channelstates. There is no way to aggregate these channelstates into anything sensible by default.

With the new implementation we will set the callerid information on the hinted speeddial to "In use remote" and set the last state provided via the lineStateChange event. This is not ideal in all cases, but give it a try and see if it works out. If you drop the second call, the state will revert to the previous information displayed.

***Git***
_Checkout this temporary branch_
```
cd /usr/src/chan-sccp
git fetch origin
git branch issues/533 origin/issues/533
git checkout issues/533
git pull
./configure [....]
make -j4 && make install && make reload
```

_move back to develop afterwards:_
```
cd /usr/src/chan-sccp
git checkout develop
git pull
./configure [....]
make -j4 && make install && make reload
```

**Comment by dkgroot** [comment]
Committed a somewhat simple fix for the second issue. It seems to work, although i don't think it's the nicest way to solve the issue.

**Comment by drtmk** [comment]
The first problem still exists. Nothing has changed.

The second problem is fixed. After answering a call with Group Pickup by Charlie, the speed dial for a moment shows `Alice -> Charlie` but it quickly updates to `Alice <=> Charlie`.

**Comment by dkgroot** [comment]
A lot has changed for the first case, but i checked the callwaiting version. I will check again with calllimit=1

Ok so second one closed.

**Comment by dkgroot** [comment]
I retested and case one seems to work for me, both with and without hitting the incomingcalllimit. Note: Currently i only have two sccp phones connected, so for the third (Charlie) i am using a sip soft phone. Can you check to make sure you are/were running in the issues/533 branch and recheck the first case. If debug is required, set "sccp debug core, channel, pbx, indicate, hint" so we can see what is going on with these two calls.

Side note: with the first commit in this branch, i made all the experimental code in sccp_hint the default, which may have a side effect on how parked calls are handled (#528) so we need to commit and merged these changes first, before re-checking the parking issues.

**Comment by drtmk** [comment]
I'm running 4.3.2 issues/533 - 26b79e6 with incominglimit=1.
When I call from A to B and during ringing state call A again from 3rd phone, speed dial with A extension shows `Bob <- Alice` but lamp becomes solid red.

[issue533.txt](https://github.com/chan-sccp/chan-sccp/files/5200820/issue533.txt)

https://drive.google.com/file/d/1iZeG3EFs7P98Ek1mm-hIgr2Kj3FYWsxc/view?usp=sharing

**Comment by dkgroot** [comment]
I recreated you dialplan with the "handle_dialstatus" macro, returning BUSY(x) to the caller. I reproduced the events in your call sequence, but i am getting a different result on the dynamic speeddial. Not sure but it might be a race condition, which in the case of hints is pretty much impossible to prevent.

I am not to worried to much about this exact case, to much, you are getting signalled about a state change on the monitored phone and with aggregate states it's mostly impossible to do the right thing in all cases (do you agree ?). And as you mentioned these are mostly cosmetic. Shall we merge the current result (with case two closed) and circle back to the parking issue ? We can come back to case 1 afterwards.

Thanks for providing the debug log + video (most helpfull). Nice to see your test case is actually using Alice, Bob and Charlie :-) These three names are used in a lot of voip and security scenarios (for example on the asterisk site) :-)

**Comment by drtmk** [comment]
I think we can merge it to development branch. It's so small bug that probably nobody will even notice it.
https://en.wikipedia.org/wiki/Alice_and_Bob

**Comment by dkgroot** [comment]
Merged, branch does not exist anymore.
Hmmm not to sure nobody will notice, i activated some experimental code (that was long overdue), which significantly changed the devicestate -> channelstate conversion. We will see :-)

**Comment by drtmk** [comment]
It's interesting. I'm not getting that red lamp from first case using 4.3.2 issues/528 - fd7d562. Still blinks orange. Tried many times. Maybe it's fixed.

**Comment by dkgroot** [comment]
I had that fixed, but i forgot to push the change last time you checked :-) Woops

**Comment by drtmk** [comment]
Can you check again that second problem (Invalid speed dial direction after answering Group Pickup). I'm gettin "Alice->Charlie" speed dial again after Group Pickup.

It's happening on 4.3.2 issues/528 - a78dea3 where this problem should be solved.

**Comment by dkgroot** [comment]
I will merge #528 first so that it's code is in develop and then re-open and rebase this branch, so that i can have a look

**Comment by dkgroot** [comment]
***Git***
_Checkout this temporary branch_
```
cd /usr/src/chan-sccp
git fetch origin
git branch issues/533 origin/issues/533
git checkout issues/533
git pull
./configure [....]
make -j4 && make install && make reload
```

Note: i made a somewhat significant change, so we may have to re-check all dynamic speeddial indications.

_move back to develop afterwards:_
```
cd /usr/src/chan-sccp
git checkout develop
git pull
./configure [....]
make -j4 && make install && make reload
```

**Comment by drtmk** [comment]
Standard dialing and Group Pickup works ok. Call plates and dynamic speed dials behave fine. So both problems are resolved in this issue #533.

I tested parking again, and there are 2 problems. Dialing parked extension shows `701 <=> Alice` in a speed dial when Alice called parked extension. There should be a name of parked party. (call plate is ok, it shows the name).
After parking a call, dynamic speed dial shows `Parkuj -> Alice` for ex. It should display `Parkuj <=> Alice`.

4.3.2 issues/533 - 351fe4b

**Comment by dkgroot** [comment]
> Standard dialing and Group Pickup works ok. Call plates and dynamic speed dials behave fine. So both problems are resolved in this issue #533.

:+1: 

> 1. Dialing parked extension shows 701 <=> Alice in a speed dial when Alice called parked extension. There should be a name of parked party. (call plate is ok, it shows the name).

> 2. After parking a call, dynamic speed dial shows Parkuj -> Alice for ex. It should display Parkuj <=> Alice.

I will check both

Note: At the moment we don't have a lot/any control over the party being parked (They can be any channel type like sip). So changing the callerid direction an information depends mainly on what asterisk sends us in this case. I have not looked into it, to see if there is a little wiggleroom there.

**Comment by dkgroot** [comment]
I do not know how to fix the second issue, to be honest (also i don't find it that problematic). The way remote hints is currently implemented, we don't have that precise controle about what and how remote calls are displayed.

**Comment by drtmk** [comment]
Ok. Works fine.
We can leave the second issue. It's not that problematic.

**Comment by dkgroot** [comment]
Merged into develop
Thanks again for reporting and testing !
