### ISSUE TITLE
Module Load Failed

### ISSUE THREAD

**Issue by cww2697** [marcelloceschia/chan-sccp-b#577]
When loading the module in asterisk 16 the following error occurs:

loader.c:170 module_load_error: Error loading module 'chan_sccp.so': /usr/lib64/asterisk/modules/chan_sccp.so: undefined symbol: ast_manager_check_enabled

no errors occur during ./configure or make stage.

**Reproduction Steps:**

1. Install using v4.3.4
2. attempt to load module using "load module chan_sccp.so"

**chan-sccp version:** 4.3.4

**asterisk version:** 16.3.0 
**asterisk package version:** asterisk16-16.19.0-1.sng7.x86_64

**Expected behavior:**

Module loads

**Observed behavior:**

Module failed to load with the above error message

**Comment by cww2697** [comment]
Issue resolved after restart of server

**Comment by dkgroot** [comment]
@cww2697 Thanks for closing the issue on your own. Good luck / Enjoy !
