### ISSUE TITLE
Not enough calls to transfer

### ISSUE THREAD

**Issue by jeremyy294** [marcelloceschia/chan-sccp-b#578]
Receiving "Not enough calls to transfer" when trying to use "DirTrfr" and not seeing "Transfer" when engaged in a call / hold.

**chan-sccp version: (include revision and/or branch if relevant)**
Using latest version from git

**asterisk version: (include revision and/or branch if relevant)**
Asterisk 16.19.0

**Expected behavior:**
Can transfer a call

**Observed behavior:**
No "Transfer" available, "DirTrfr" shows "Not enough calls to transfer"

Appreciate any advice

**Comment by dkgroot** [comment]
@jeremyy294 
Is tranfer enabled for this phone ? `sccp show device XXXXX` should have `Can Transfer : on`. What is the `Softkeyset                                   ` set to for this phone ?
If you have an active call from 1234 to 2345 on SEPxxxxxx, which you have answered, you should see the 'Transfer' button on the phone as one of the softkeys. If you have changed the softkeyset then this button might not be available in the set and state you are in. If you are using the `default` softkeyset it should be there.
Once you press `Transfer` you get a new call + dialtone and you have to enter the destination. You can not speak to the second person and when finished you can press `Transfer` again to complete the transfer.

**Comment by jeremyy294** [comment]
@dkgroot 

Strangely, transfer is enabled and using default softkey set, but still cannot see Transfer when engaged in a call.

Can Transfer : on
Softkey support : yes
Softkeyset : default => default (0x33b05f0)

**Comment by dkgroot** [comment]
Ooh that is strange.
Can you set `sccp debug core, action, device, line, channel, pbx, softkey, indicate` in the CLI  and perform one of these calls ? Would like to see what is going on. What type of phone are we talking about btw?
Might be easier to deal with this via https://gitter.im/chan-sccp/chan-sccp so we can communicate directly

**Comment by beom80** [comment]
I am having a very similar issue. It was working under an older version of Asterisk and chan-sccp (I can't recall the versions) and I updated to Asterisk 16.21.1 and chan-sccp 4.3.5 r433 and SCCP-Manager 14.3.0.13

I get the transfer button showing with either an active call or the call is on hold but when pressed it says 'Key Is Not Active' and DirTrfr shows the same 'not enough calls to transfer'

Phones are Cisco 7912/7940/7960's
