### ISSUE TITLE
Unable to register first SCCP phone

### ISSUE THREAD

**Issue by astifr** [marcelloceschia/chan-sccp-b#583]
Hi all, I'm testing chan_sccp with a fresh install FreePBX. I follow the guide from https://github.com/chan-sccp/chan-sccp/wiki/FreePBX and I think that I have my system properly configured.
I have one Cisco phone 7965 configured under SCCP Connectivity -> Phone Manager -> SCCP Phone
But I think that i'm missing something because I can see an error under fail2ban log,
[2021-10-19 11:41:50] NOTICE[20147] sccp_actions.c: SEP2C0BE90440B0: Rejecting device: Device Unknown

I noted that in the file sccp.conf I don't have any entry for the device. I don't if it's correct or not.

I'm using latest version of chan_sccp (downloaded yesterday) and FreePBX 15.0.17.55 with asterisk 16.

Thank you in advence.

**Comment by waffle-stomper** [comment]
@astifr

**Edit: I managed to solve the 'Rejecting device: Device Unkown' error by doing the following:**

Adding this to /etc/asterisk/extconfig_custom.conf:

```
[settings]
;[alias] => [driver],[dbsection],[dbtablename]
sccpdevice => mysql,myastdb,sccpdeviceconfig
sccpline => mysql,myastdb,sccpline
```

Adding this to /etc/asterisk/res_config_mysql.conf (note that I also created this DB user and granted it full permissions for the asterisk db):

```
[myastdb]
dbsock = /var/lib/mysql/mysql.sock
dbname = asterisk
dbuser = my_username
dbpass = hunter2
requirements = warn
```

~~I'm having the same issue with a Cisco 7962G running the cmterm-7942_7962-sccp.9-4-2SR3-1 firmware on Asterisk 16.20.0/FreePBX 15.0.17.34/chan-sccp 4.3.4 develop - b0b3cdb.~~

~~/var/log/asterisk/full shows the following:~~

```
[2021-11-25 22:54:15] VERBOSE[3867] :  SEP[phone_mac]: is registering, Instance: 0, UserId: 0, Type: Cisco 7962 (404), Version: 22 (loadinfo 'term62.default')
[2021-11-25 22:54:15] VERBOSE[3867] :     -- SCCP: Device 'SEP[phone_mac]' not found in realtime table 'sccpdevice'
[2021-11-25 22:54:15] NOTICE[3867] sccp_actions.c: SEP[phone_mac]: Rejecting device: Device Unknown 
```

**Comment by dkgroot** [comment]
@astifr @waffle-stomper 
It sounds like you might be using and older version of sccp_manager. You ought to be clone https://github.com/chan-sccp/sccp_manager or download it's latest release from https://github.com/chan-sccp/sccp_manager/releases/tag/v14.2.0.3. This newer version should automatically check and setup realtime for you and would make the same changes described by @waffle-stomper . The changes made by @waffle-stomper manually are fine and would also work, but should not be required anymore using the latest version.

@waffle-stomper Thanks for helping out another member of our community.
@astifr Please close this issue ticket if/once you issue is resolved. If you are still experiencing problems, do let us know.

**Comment by waffle-stomper** [comment]
@dkgroot 

Thanks for the quick response, and for all of your hard work on this project.

> It sounds like you might be using and older version of sccp_manager.

I think you're right - I was using Legacy-v2.tar.gz which was recommended on this page in the wiki: https://github.com/chan-sccp/chan-sccp/wiki/FreePBX_SCCP-modules

I considered v14.x but I read that it would require upgrading PHP to v7 and I was worried that might break my FreePBX install.

**Comment by dkgroot** [comment]
@waffle-stomper Yes the php update/upgrade is a requirement, but if you don't already have it, i would assume your FreePBX install is in need of a little update as well. If you are running on a VM, you should be able do a bulkexport on your current install, start a new installation with updated OS and FreePBX and then proceed to use bulkimport to get everything back up and running.

Note: I am not a FreePBX user, so i am just guessing at this point ! Steve and Alex are in the know and they might be the better advisors here.

**Comment by steve-lad** [comment]
FreePbx 16 is now GA, and there is an upgrade tool from 15, so the best path is to upgrade FreePbx, and then install 14.3. That will resolve any issues with the flat file configuration.

@astifr Normally you do not need a new db user - just use the freepbx user. 14.3 will take care of this

**Comment by dkgroot** [comment]
@steve-lad Thanks for your guidance !
@astifr If you are running on/in a VM, it's always wise to snapshot or clone before making modifications, just so you have something to fall back on. Backup's are a good thing :-)

**Comment by astifr** [comment]
Thank you all for your support. I´ll try as soon as possible.
