### ISSUE TITLE
No ringout sound when calling outside

### ISSUE THREAD

**Issue by Blancandrin** [marcelloceschia/chan-sccp-b#594]
[Short description of problem here]

When I use a Cisco 7970 ip phone to make an outside call, there is no ringout sound when the outside phone is ringing. When the call is answered, everything works fine.

**Reproduction Steps:**

I just need to make a call outside of my Asterisk server with one of my Cisco 7970 phone to reproduce this issue. I can't hear anything when the outside phone is rigning, but we can talk normally when the call is answered.
 
If I try it with a pjsip phone, it works without any problem.

**chan-sccp version:** 
4.3.5 develop

**asterisk version:** 
18.6.0

**Expected behavior:**
I should be able to hear a ringout sound when I am calling outside of my Asterisk server.

[Describe expected behavior here]

**Observed behavior:**
I cannot hear a ringout sound when I am calling outside of my Asterisk server.

[Describe observed behavior here]

**Screenshots**

(Screenshots which show reproduction steps and/or demonstrate the problem)
[url]

**Addition / Optional Information:**
- Problem started happening recently, didn't happen in an older version of Chan-SCCP: [Yes/No] No, on another server with chan-sccp 4.3.1 develop, it works fine.
- Problem can be reliably reproduced, doesn't happen randomly: [Yes/No] Yes
- Platform:
  - [CPU] Intel(R) Atom(TM) CPU D2550   @ 1.86GHz
  - [32/64 Bit] 64 Bit
  - [Big/Small Endian]
  - [Operating System] Centos
  - [Operating System Version] 7 Core
- Direct Contact information: [You can contact me here]
- Log Files (attach .txt / [pastbin](http://pastebin.com/) / [gist](http://gist.github.com/)): [url]
- Comments: [Other Information]
I am running Asterisk with FreePBX 16.0.10.43

**BTW: Consider making a donation via paypal:**
- https://www.paypal.com/cgi-bin/webscr?&cmd=_donations&business=chan.sccp.b.pp%40gmail.com

**Comment by mfmkhatri** [comment]
Were you able to solve this issue? I am facing the same issue. I have spent several days trying different configurations, but I still haven't been able to solve this issue.
